### PR TITLE
Let signatures take an image representing the actual signature

### PR DESCRIPTION
**Pull request by fnurkla**
This is a work in progress as it gives ugly results when the signature is too wide.

### CODE REVIEW

**Comment by fnurkla** [comment]
Results are now much better:
image
but there are misalignments when the message above the signature has descenders:
image

**Comment by fnurkla** [comment]
Alignments seem to be solved now:
image

**Comment by alfredgrip** [comment]
This looks really neat! However, I noticed that when there are multiple signatures (like 5+) and they break line, there is barely and margin between the one above and the one below. Would be nice to have.

Screenshot 2023-12-29 at 13 35 27

**Comment by fnurkla** [comment]
Added a small space now: 
image

**Comment by alfredgrip** [comment]
LGTM!

**Pull request merged**
