### PR TITLE
Add motion/proposition document class

### PR DESCRIPTION
**Pull request by alfredgrip**
This is a proposal for a document class for "motion". Since a "proposition" is basically the same (just other another title) the document class takes in it as an option, but defaults to motion.

Feel free to make changes both to the structure and/or nameings. I thought of naming the class `dsekproposal`, since this has the option to be either a "motion" or a "proposition", and making two different document classes for the options seemed unnecessary. I like the name `dsekmotion` though since its very self-explaining.

Of course the documentations would have to be updated for this as well, maybe something you can do @fnurkla?

I also included an example of how this document class can be used.

### CODE REVIEW

**Comment by alfredgrip** [comment]
Linked to issue #7

**Comment by fnurkla** [comment]
Good job! My only feedback would be that I am unsure whether I find the `\setdemand{...}` and `\usedemand` commands very necessary. I know they existed in the old motion template, but I found them a bit weird there too; just write demand in plain text.  Are there any specific use cases I'm missing?

**Comment by alfredgrip** [comment]
No that is true, I mostly looked at the old templates and tried to copy it over. But yeah I don't see any other use cases for the demand except for including it before the "att-satser", but as you say it could just be included in the body of the document as plain text.

On another note, do you have any thoughts on including in the document class whether a proposal is late or note? ("Sen handling") As far as I know, we have no defined way to mark a proposal as late. These are the options I see:
1. Don't mark it in the document at all. The document itself doesn't need to tell that it's late, rather it should marked or said on the meeting it is brought up on.
2. Mark it in the short title
3. Mark it both in the short title and the title, i.e. ("Sen motion: Världens bästa förslag")

IMO option 1 makes most sense to me, since any form of document is late only if the meeting treats it as late. But the document itself doesn't need to include that.

**Comment by fnurkla** [comment]
I agree that option 1 makes the most sense and is how praxis looks today iirc. Do you mind removing the `\setdemand{...}`, `\usedemand`? Then I'll merge the branch straight up.

**Pull request merged**
